export const MARKET_LANDS = [
  {
    "title": "Residential",
    "line": "Homes, plots and NA land",
    "image": "/images/market-residential.jpg",
    "alt": "Residential land and plots",
    "note": "NA / plots",
    "status": "14 parcels"
  },
  {
    "title": "Agribusiness / Industry",
    "line": "Agri-industry holdings",
    "image": "/images/market-commercial.jpg",
    "alt": "Agribusiness and industry land",
    "note": "Agri-industry",
    "status": "1 parcel"
  },
  {
    "title": "Agriculture",
    "line": "Farmland and open acreage",
    "image": "/images/market-agricultural.jpg",
    "alt": "Agricultural farmland",
    "note": "Farmland",
    "status": "13 parcels"
  },
  {
    "title": "Regional Park",
    "line": "Park and reserved land",
    "image": "/images/pavilion.jpg",
    "alt": "Regional park land",
    "note": "Park",
    "status": "1 parcel"
  },
  {
    "title": "Forest",
    "line": "Forest and tree land",
    "image": "/images/forest.jpg",
    "alt": "Forest land holding",
    "note": "Forest",
    "status": "2 parcels"
  },
  {
    "title": "Industrial",
    "line": "Industrial and DP-road land",
    "image": "/images/market-industrial.jpg",
    "alt": "Industrial land",
    "note": "Industry",
    "status": "2 parcels"
  }
]

export const PARCELS = [
  {
    "id": "101",
    "owner": "NKG",
    "location": "SUS",
    "taluka": "Mulshi",
    "district": "Pune",
    "surveyNo": "214/1",
    "area": "7 Acres",
    "landType": "Open NA Land",
    "frontage": "305 feet - 60 M road 640 feet - 24 M road",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "DONE",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Title Search Done",
    "demand": "Re. Deposit - 30 Cr Residential - 60 / 40 Commercial - 50 /50",
    "projectType": "JV",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/market-residential.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "102",
    "owner": "NKG",
    "location": "FC ROAD",
    "taluka": "Pune City",
    "district": "Pune",
    "surveyNo": "925 To 929",
    "area": "4.5 Acres",
    "landType": "NA, Owner and Lessee hold",
    "frontage": "492 feet - 30 M road 6 M wide internal road",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "DONE",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "Re. Deposit - 50 Cr ESCROW Acc. - 150 Cr Residential - 60 / 40 Commercial - 50 /50",
    "projectType": "JV",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/aerial.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "103",
    "owner": "NKG",
    "location": "MAMURDI",
    "taluka": "Haveli",
    "district": "Pune",
    "surveyNo": "6/7/B,C, 6/8, 6/9, 7/1/A,B,C, 8, 9/1,2, 10/1/2",
    "area": "42.6 Acres",
    "landType": "Open NA land",
    "frontage": "500 M - 9 M Service Road and 6 Lane Mumbai -Pune expressway 14 M - DP Road passes through all sides of the site",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "DONE",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/terrace.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "104",
    "owner": "NKG",
    "location": "WALEN",
    "taluka": "Maval",
    "district": "Pune",
    "surveyNo": "",
    "area": "460 Acres",
    "landType": "Open Agriculture Land",
    "frontage": "",
    "onePager": "",
    "zoning": "",
    "reservation": "",
    "potential": "",
    "photos": "",
    "video": "",
    "titleStatus": "",
    "titleReport": "",
    "demand": "",
    "projectType": "JV",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/market-agricultural.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "105",
    "owner": "O - Prashit Barhate",
    "location": "BAVADHAN(KH)",
    "taluka": "Mulshi",
    "district": "Pune",
    "surveyNo": "49/2,6",
    "area": "2.5 Acres",
    "landType": "Open NA Land",
    "frontage": "700 feet - 24 M Road",
    "onePager": "",
    "zoning": "",
    "reservation": "Otta MKT and Bus Stop",
    "potential": "DONE",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "MPID",
    "titleReport": "DONE",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "22 Mar 2026",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/orchard.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "106",
    "owner": "O - Prashit Barhate",
    "location": "CHENE",
    "taluka": "Thane",
    "district": "Thane",
    "surveyNo": "63/3 & 65/1,2",
    "area": "2.3 Acres",
    "landType": "Open NA Land",
    "frontage": "Proximity to a 12-meter-wide DP road.",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "DONE",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "MPID",
    "titleReport": "DONE",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "22 Mar 2026",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/plantation.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "107",
    "owner": "O - Prashit Barhate",
    "location": "GADIKHEL SHIRSUFAL",
    "taluka": "Baramati",
    "district": "Pune",
    "surveyNo": "Gadikhel - 36,37,41, 42, 43, 45, 46, 49, 51, 53, 320 & 321 Shirsufal - 649, 650, 652, 673, 686, 689, 792, 793, 795, 796, 797, 798 & 799",
    "area": "400 Acres",
    "landType": "Agriculture",
    "frontage": "1 Km - 6 M Road",
    "onePager": "DONE",
    "zoning": "Agribusiness / Industry",
    "reservation": "NA",
    "potential": "Pending",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "MPID",
    "titleReport": "DONE",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "22 Mar 2026",
    "contactNote": "",
    "banks": [
      "Agribusiness / Industry"
    ],
    "image": "/images/market-commercial.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "108",
    "owner": "A - Nirav Jani",
    "location": "MULUND",
    "taluka": "Kurla",
    "district": "Mumbai Upnagar",
    "surveyNo": "1109 To 1125",
    "area": "54 Acres",
    "landType": "NA & 21 Acres Open land",
    "frontage": "280 M - 18 M LBS Marg 900 M - 18 M Din Dayal Road 9 M Wide road passes though out Site",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "Fire Station, Bus depot, MSEB & Ground",
    "potential": "Pending",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "LITIGATION",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/kharadi-it-corridor.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "109",
    "owner": "A - Nikhil Oak &",
    "location": "MALAD",
    "taluka": "Borivali",
    "district": "Mumbai Upnagar",
    "surveyNo": "307/46/31, 32, 33 & 34",
    "area": "2.74 Acres",
    "landType": "NA Open Land",
    "frontage": "300 Feet - 9 M Road (Ramchandra Lane) Poisar River Front",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "Garden",
    "potential": "DONE",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "LITIGATION / All Party Consent Terms to Nikhil Oak",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/token-urban.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "110",
    "owner": "A - Naren Tiwari",
    "location": "VIRAR",
    "taluka": "Vasai",
    "district": "Palghar",
    "surveyNo": "376/1",
    "area": "10.5 Acres",
    "landType": "NA Open Land",
    "frontage": "140 M - 14 M road 260 M - 6 M road Opp. to Vasai Virar Muncipal Office",
    "onePager": "NO",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "NO",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/lake.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "111",
    "owner": "A - B. K. Sing",
    "location": "VADAVALI",
    "taluka": "Kalyan",
    "district": "Thane",
    "surveyNo": "54/A/1, 54/A/2, 64/5/1, 64/6/A, 99/6 to 99/8, 99/9/A, 99/9B, 99/10, 99/11, 99/12B, 99/13 to 99/22",
    "area": "20.76 Acres",
    "landType": "NA Open Land",
    "frontage": "400 M - 30 M Road 350 M - 9 M Road",
    "onePager": "NO",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "DONE",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "LITIGATION",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/valley.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "112",
    "owner": "Owner on file",
    "location": "PADASALI",
    "taluka": "Radhanagari",
    "district": "Kolhapur",
    "surveyNo": "37,38, 42 to 48, 56 to 66, 70 to 74, 92, 95, 97, 99, 101, 103,104, 183,184 and 185",
    "area": "2,477 Acres",
    "landType": "Farmland",
    "frontage": "Village road",
    "onePager": "DONE",
    "zoning": "Agriculture",
    "reservation": "Dhamani Project land not for sale without permission.",
    "potential": "NO",
    "photos": "NO",
    "video": "DONE",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/path.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "113",
    "owner": "O - Shivraj Patil",
    "location": "HADAPSAR",
    "taluka": "Haveli",
    "district": "Pune",
    "surveyNo": "124,246 and 282",
    "area": "49 Acres",
    "landType": "NA Open Land",
    "frontage": "770 M - 24 M Road 18 M - DP Road passes through site (300M)",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "Slum",
    "potential": "DONE",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "LITIGATION (High Court)",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/forest.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "114",
    "owner": "A - J. K. Bhai & Algotar",
    "location": "ADIVALI",
    "taluka": "Panvel",
    "district": "Raigad",
    "surveyNo": "5, 33,37,42,89,90",
    "area": "54 Acres",
    "landType": "NA Open Land",
    "frontage": "500 Feet - 60 M Road",
    "onePager": "DONE",
    "zoning": "Residential",
    "reservation": "Ground",
    "potential": "NO",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "LITIGATION (Revenue Court )",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/ridge.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "115",
    "owner": "A -Naren Tiwari",
    "location": "KARANJADE",
    "taluka": "Panvel",
    "district": "Raigad",
    "surveyNo": "67/1, 69/2, 76/2, 78/1, 79, 80, 81/1, 82/1/2, 83, 84, 85/1, 86, 87/3, 88/2, 94/1, 94/2, 95/1/A, 96/2/A, 98/3, 99/4, 126/6",
    "area": "103 Acres",
    "landType": "Open land",
    "frontage": "650 M - 60 M Road and 9 M service Road",
    "onePager": "DONE",
    "zoning": "Regional Park",
    "reservation": "NA",
    "potential": "NO",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "LITIGATION (High Court, Hatthiram Trust)",
    "titleReport": "DONE",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Regional Park"
    ],
    "image": "/images/sunrise.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "116",
    "owner": "A -Naren Tiwari",
    "location": "CHINCHVAN",
    "taluka": "Panvel",
    "district": "Raigad",
    "surveyNo": "31 To 47",
    "area": "872 Acres",
    "landType": "Open land",
    "frontage": "400 + M - Mumbai Goa Highway",
    "onePager": "NO",
    "zoning": "Residential + Forest",
    "reservation": "Forest",
    "potential": "NO",
    "photos": "NO",
    "video": "YES",
    "titleStatus": "Forest and 32 G",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Forest",
      "Residential"
    ],
    "image": "/images/soil.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "117",
    "owner": "O - Vinit Malhotra & A - Mane (PSI)",
    "location": "ODHANGI, DHONDPADA & More",
    "taluka": "Pen",
    "district": "Raigad",
    "surveyNo": "UDACHIVADI, UCHEDE, WADAKHAL and Nearby Villages",
    "area": "450 Acres",
    "landType": "Open land",
    "frontage": "190 M - Mumbai Goa Highway 1.5 Km - Washi Vadhav Road",
    "onePager": "NO",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "YES",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "",
    "titleReport": "",
    "demand": "",
    "projectType": "JV OR OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/market-industrial.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "118",
    "owner": "A - Rajaram",
    "location": "KURZE (Wadhawan)",
    "taluka": "Talsari",
    "district": "Palghar",
    "surveyNo": "117 to 119, 125, 126/3, 128, 266, 354, 355/2, 356/3,4, 357, 358/3, 359/1, 361/7, 375 and 415",
    "area": "215 Acres",
    "landType": "Open Land",
    "frontage": "Village road",
    "onePager": "DONE",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/token-highway.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "119",
    "owner": "O - Ranjit Jamdade",
    "location": "GUNDALWADI",
    "taluka": "Khed",
    "district": "Pune",
    "surveyNo": "66",
    "area": "28 Acres",
    "landType": "Open land",
    "frontage": "Village road (Chaskaman Dam View )",
    "onePager": "NO",
    "zoning": "Forest",
    "reservation": "Forest",
    "potential": "NO",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "Forest",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Forest"
    ],
    "image": "/images/pavilion.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "120",
    "owner": "A - B. K. Sing",
    "location": "CHINCHAVALI",
    "taluka": "Ambernath",
    "district": "Thane",
    "surveyNo": "105",
    "area": "36 Acres",
    "landType": "Open land",
    "frontage": "9 M wide Village Road",
    "onePager": "NO",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/hero-platform.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "121",
    "owner": "A - Amar Rasal & Sul",
    "location": "DHANAKAL",
    "taluka": "Patan",
    "district": "Satara",
    "surveyNo": "29, 38, 39, 40, 41, 43, 45/1, 46/1",
    "area": "145 Acres",
    "landType": "Open land with Forest",
    "frontage": "Access road from Patan - Ratnagiri Highway",
    "onePager": "NO",
    "zoning": "Agriculture",
    "reservation": "Trees",
    "potential": "NO",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/token-scenic.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "122",
    "owner": "A - Amar Rasal & Sul",
    "location": "JAOLI",
    "taluka": "Phaltan",
    "district": "Satara",
    "surveyNo": "116/2/B",
    "area": "116 Acres",
    "landType": "Open land",
    "frontage": "Village road access. Adjacent to Village dam",
    "onePager": "NO",
    "zoning": "Agricluture",
    "reservation": "Use for only for Agriculture Purpose",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "2.5 Lakh/ Acre",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/token-agriculture.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "123",
    "owner": "A - Amar Rasal & Sul",
    "location": "MARUL TARF PATAN",
    "taluka": "Patan",
    "district": "Satara",
    "surveyNo": "558",
    "area": "20 Acres",
    "landType": "Open Land",
    "frontage": "9 M wide planned Village Road",
    "onePager": "YES",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "NO",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "16 Lakh/ Acre",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/location.jpeg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "124",
    "owner": "A - Baba Shinde & Inamdar",
    "location": "PADVEWADI",
    "taluka": "Ratnagiri",
    "district": "Ratnagiri",
    "surveyNo": "14/3, 19/3, 20/2/1, 22/2, 27/5/2,8,14, 3/9/2/4/9/3/6, 3/9/2/5, 3/9/3/8, 3/9/2/6/9/3/9, 31/1/20, 32/2/10",
    "area": "47.8 Acres",
    "landType": "Open Land",
    "frontage": "Village road access",
    "onePager": "NO",
    "zoning": "Agriculture",
    "reservation": "Trees",
    "potential": "NO",
    "photos": "YES",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "JV/OUTRIGHT",
    "quotation": "",
    "date": "05 Jan 2026",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/market-residential.jpg",
    "phone": "7218637899",
    "contactName": "Baba Shinde",
    "contactCity": "Pune"
  },
  {
    "id": "125",
    "owner": "A - Shivnekar",
    "location": "TAKAWE (BK)",
    "taluka": "Maval",
    "district": "Pune",
    "surveyNo": "238,239 & 240",
    "area": "30.16 Acres",
    "landType": "Open Land",
    "frontage": "1500 Feet - 15 M Road",
    "onePager": "YES",
    "zoning": "Industrial",
    "reservation": "NA",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "4 Cr/ Acre",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Industrial"
    ],
    "image": "/images/aerial.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "126",
    "owner": "O - Harshavardhan Jawade",
    "location": "GHODASGAON",
    "taluka": "Muktainagar",
    "district": "Jalgaon",
    "surveyNo": "405/1/1, 405/2/2 & 406",
    "area": "12.5 Acres",
    "landType": "Agriculture land",
    "frontage": "400 feet - 6 M Road",
    "onePager": "YES",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "NO",
    "photos": "YES",
    "video": "YES",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "32 Lakh/ Acre",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/terrace.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "127",
    "owner": "A - Rajaram",
    "location": "MHALUNGHE",
    "taluka": "Mulashi",
    "district": "Pune",
    "surveyNo": "36/2/1, 36/2/2 & 36/2/3",
    "area": "3 Acre",
    "landType": "NA Open Land",
    "frontage": "400 Feet - 24 M DP Road",
    "onePager": "YES",
    "zoning": "Residential",
    "reservation": "NA",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear (MPID)",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/market-agricultural.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "128",
    "owner": "Owner on file",
    "location": "KAWATHE YAMAI",
    "taluka": "Shirur",
    "district": "Pune",
    "surveyNo": "512",
    "area": "8.77 Acres",
    "landType": "Open Land",
    "frontage": "Village road",
    "onePager": "YES",
    "zoning": "Agriculture",
    "reservation": "NA",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "",
    "titleReport": "",
    "demand": "23 Lakh/ Acre",
    "projectType": "OUTRIGHT",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/orchard.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "129",
    "owner": "Somnath Mohite",
    "location": "KARLA & DEVGHAR",
    "taluka": "Maval",
    "district": "Pune",
    "surveyNo": "487 & 98,99,100,108,110 to 114",
    "area": "51 Acres",
    "landType": "Open Land",
    "frontage": "South Side: Approximately 2,000 ft continuous frontage along the 60-metre-wide, 4-lane Old Pune–Mumbai Highway, with an additional 12-metre-wide service road. East Side: Approximately 1,600 ft continuous frontage along a 15-metre-wide DP Road passing along the eastern boundary of the plot. North Side: Approximately 1,400 ft continuous frontage along a 15-metre-wide DP Road passing along the northern boundary of the plot. West Side: Approximately 2,000 ft continuous frontage along a 12-metre-wide DP Road passing along the western boundary of the plot.",
    "onePager": "NO",
    "zoning": "Residential",
    "reservation": "",
    "potential": "",
    "photos": "",
    "video": "",
    "titleStatus": "",
    "titleReport": "",
    "demand": "",
    "projectType": "",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Residential"
    ],
    "image": "/images/plantation.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "130",
    "owner": "Sanjay Choudhary",
    "location": "KALOTE MOKASHI",
    "taluka": "Panvel",
    "district": "Raigad",
    "surveyNo": "",
    "area": "",
    "landType": "",
    "frontage": "",
    "onePager": "NO",
    "zoning": "",
    "reservation": "",
    "potential": "",
    "photos": "",
    "video": "",
    "titleStatus": "",
    "titleReport": "",
    "demand": "",
    "projectType": "",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/market-commercial.jpg",
    "phone": "9560870007",
    "contactName": "Sanjay Choudhary",
    "contactCity": ""
  },
  {
    "id": "131",
    "owner": "Somnath Mohite",
    "location": "KANHE",
    "taluka": "Maval",
    "district": "Pune",
    "surveyNo": "307 to 401, 403 to 406, and 408 & 409",
    "area": "91 Acres",
    "landType": "Open Land",
    "frontage": "Approximately 700 ft continuous frontage along the 22-36-metre-wide DP Road. Appproximately 1400 ft continuous frontage along the Indrayani River",
    "onePager": "NO",
    "zoning": "Industrial",
    "reservation": "Blue and Red Flood Line",
    "potential": "NO",
    "photos": "NO",
    "video": "NO",
    "titleStatus": "Clear",
    "titleReport": "Pending",
    "demand": "",
    "projectType": "",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Industrial"
    ],
    "image": "/images/kharadi-it-corridor.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  },
  {
    "id": "132",
    "owner": "Owner on file",
    "location": "SOMATANE, DAHIWALI & BHATAN",
    "taluka": "Panvel",
    "district": "Raigad",
    "surveyNo": "",
    "area": "",
    "landType": "Open Land",
    "frontage": "",
    "onePager": "",
    "zoning": "",
    "reservation": "",
    "potential": "",
    "photos": "",
    "video": "",
    "titleStatus": "",
    "titleReport": "",
    "demand": "",
    "projectType": "",
    "quotation": "",
    "date": "",
    "contactNote": "",
    "banks": [
      "Agriculture"
    ],
    "image": "/images/token-urban.jpg",
    "phone": "",
    "contactName": "",
    "contactCity": ""
  }
]

export function landUseSlug(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

export function landUseFromSlug(slug) {
  return MARKET_LANDS.find((item) => landUseSlug(item.title) === slug)?.title || ""
}

export function parcelsForSlug(slug) {
  const title = landUseFromSlug(slug)
  return title ? PARCELS.filter((item) => item.banks.includes(title)) : []
}

export function parcelById(slug, parcelId) {
  return parcelsForSlug(slug).find((item) => item.id === String(parcelId)) || null
}
